# fly.toml app configuration file generated for raffle-luteranos-ddd-fragrant-leaf-9861 on 2024-06-21T14:57:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'raffle-luteranos-ddd'
primary_region = 'gig'

[build]
  dockerfile = "docker/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
