spring:
  application:
    name: raffle-luteranos-ddd

  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
app:
  imgur:
    url: https://api.imgur.com
    client-id: ${IMGUR_CLIENT_ID}
  mercadopago:
    type-token: Bearer
    api-key: ${MP_API_KEY}
