spring:
  application:
    name: raffle-luteranos-ddd

  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
app:
  imgur:
    url: https://api.imgur.com
    client-id: 9522ec40ca7240c