version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: raffle-luteranos
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"